/**
 * Database Seeder
 * Run: node seed.js
 * Seeds admin user, bikes, and services into MongoDB
 */
require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const connectDB = require('./config/db');
const User = require('./models/User');
const Bike = require('./models/Bike');
const Service = require('./models/Service');

const seed = async () => {
  await connectDB();
  console.log('🌱 Starting database seeder...\n');

  try {
    // Clear existing data
    await Promise.all([User.deleteMany(), Bike.deleteMany(), Service.deleteMany()]);
    console.log('🗑️  Cleared existing data');

    // ─── Admin User ──────────────────────────────────────
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@motorbike.com',
      password: 'admin123',
      role: 'admin',
    });
    console.log(`✅ Admin created: ${admin.email} / password: admin123`);

    // ─── Bikes ───────────────────────────────────────────
    const bikes = await Bike.insertMany([
      {
        modelName: 'Ninja ZX-10R',
        brand: 'Kawasaki',
        price: 1599000,
        engineCapacity: '998cc',
        image: 'bike1.jpg',
        category: 'Sport',
        color: 'Lime Green',
        availability: true,
        description: 'The ultimate supersport machine with race-derived technology and stunning performance.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '203 bhp @ 13,500 rpm',
          torque: '114.9 Nm @ 11,400 rpm',
          transmission: '6-speed',
          fuelCapacity: '17 litres',
          weight: '207 kg',
          topSpeed: '299 km/h',
          brakes: 'Dual disc front, single disc rear',
          suspension: 'KYB inverted fork front, KYB rear',
          tyres: '120/70-ZR17 front, 190/55-ZR17 rear',
        },
        features: ['Cornering ABS', 'Traction Control', 'Power Modes', 'Launch Control', 'Quick Shifter', 'IMU'],
      },
      {
        modelName: 'CBR1000RR-R Fireblade',
        brand: 'Honda',
        price: 1999000,
        engineCapacity: '1000cc',
        image: 'bike2.jpg',
        category: 'Sport',
        color: 'Grand Prix Red',
        availability: true,
        description: 'Honda\'s flagship superbike with MotoGP-derived aerodynamics and electronics.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '217 bhp @ 14,500 rpm',
          torque: '113 Nm @ 12,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '16.1 litres',
          weight: '201 kg',
          topSpeed: '299 km/h',
          brakes: 'Brembo Stylema calipers',
          suspension: 'Öhlins NPX fork, Öhlins TTX36 rear',
          tyres: '120/70-ZR17 front, 200/55-ZR17 rear',
        },
        features: ['Winglets', 'Honda Selectable Torque Control', 'Wheelie Control', 'Engine Brake Control', 'Launch Control', 'Öhlins Smart EC 2.0'],
      },
      {
        modelName: 'Panigale V4',
        brand: 'Ducati',
        price: 2299000,
        engineCapacity: '1103cc',
        image: 'bike3.jpg',
        category: 'Sport',
        color: 'Ducati Red',
        availability: true,
        description: 'Italian masterpiece with Desmosedici Stradale engine straight from MotoGP.',
        specifications: {
          engine: 'Desmosedici Stradale V4 90°',
          power: '215 bhp @ 13,000 rpm',
          torque: '124 Nm @ 10,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '16 litres',
          weight: '198 kg',
          topSpeed: '299 km/h',
          brakes: 'Brembo Stylema monobloc',
          suspension: 'Öhlins NIX30 fork, Öhlins TTX36 rear',
          tyres: '120/70-ZR17 front, 200/60-ZR17 rear',
        },
        features: ['Cornering ABS EVO', 'Ducati Traction Control EVO', 'Ducati Wheelie Control EVO', 'Launch Control', 'Bi-directional Quick Shift', 'Aerodynamic wings'],
      },
      {
        modelName: 'MT-09',
        brand: 'Yamaha',
        price: 899000,
        engineCapacity: '890cc',
        image: 'bike4.jpg',
        category: 'Naked',
        color: 'Midnight Black',
        availability: true,
        description: 'The Dark Side of Japan — aggressive naked bike with CP3 triple-cylinder engine.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, CP3 inline-3',
          power: '119 bhp @ 10,000 rpm',
          torque: '93 Nm @ 7,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '14 litres',
          weight: '193 kg',
          topSpeed: '215 km/h',
          brakes: 'Dual disc front, single disc rear',
          suspension: 'KYB inverted fork, KYB rear',
          tyres: '120/70-ZR17 front, 180/55-ZR17 rear',
        },
        features: ['3 Power Modes', 'Traction Control', 'Slide Control', 'Quick Shift', 'D-Mode', 'LED Lighting'],
      },
      {
        modelName: 'Fat Boy 114',
        brand: 'Harley-Davidson',
        price: 1750000,
        engineCapacity: '1868cc',
        image: 'bike5.jpg',
        category: 'Cruiser',
        color: 'Vivid Black',
        availability: true,
        description: 'The iconic American cruiser with solid-disc wheels and Milwaukee-Eight powerplant.',
        specifications: {
          engine: 'Milwaukee-Eight 114 V-Twin',
          power: '98 bhp @ 5,020 rpm',
          torque: '161 Nm @ 3,000 rpm',
          transmission: '6-speed Cruise Drive',
          fuelCapacity: '18.9 litres',
          weight: '317 kg',
          topSpeed: '180 km/h',
          brakes: 'Twin floating rotors front, fixed rotor rear',
          suspension: 'Telescopic fork, twin rear shock',
          tyres: '160/70-B17 front, 240/40-R18 rear',
        },
        features: ['ABS', 'Reflex Defensive Rider Systems', 'Drag Bars', 'LED Lighting', 'Infotainment System', 'Heritage Styling'],
      },
      {
        modelName: 'Africa Twin CRF1100L',
        brand: 'Honda',
        price: 1350000,
        engineCapacity: '1084cc',
        image: 'bike6.jpg',
        category: 'Adventure',
        color: 'Pearl Glare White',
        availability: true,
        description: 'Legendary adventure tourer ready for any terrain, inspired by Dakar Rally DNA.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, parallel-twin',
          power: '101 bhp @ 7,500 rpm',
          torque: '105 Nm @ 6,250 rpm',
          transmission: '6-speed + DCT option',
          fuelCapacity: '24.8 litres',
          weight: '226 kg',
          topSpeed: '220 km/h',
          brakes: 'Dual floating disc front, single disc rear',
          suspension: 'Showa SFF-CA 45mm fork, Pro-Link rear',
          tyres: '90/90-21 front, 150/70-R18 rear',
        },
        features: ['Dual Clutch Transmission', 'Cornering ABS', 'ATRC Traction Control', 'Wheelie Control', 'Hill Start Assist', 'Apple CarPlay'],
      },
      {
        modelName: 'R 1250 GS Adventure',
        brand: 'BMW',
        price: 2100000,
        engineCapacity: '1254cc',
        image: 'bike7.jpg',
        category: 'Adventure',
        color: 'Ice Grey',
        availability: true,
        description: 'The world\'s most popular adventure motorcycle with ShiftCam technology.',
        specifications: {
          engine: 'Air/liquid-cooled Boxer twin',
          power: '136 bhp @ 7,750 rpm',
          torque: '143 Nm @ 6,250 rpm',
          transmission: '6-speed',
          fuelCapacity: '30 litres',
          weight: '268 kg',
          topSpeed: '220 km/h',
          brakes: 'Twin disc front, single disc rear',
          suspension: 'BMW Telelever, EVO Paralever',
          tyres: '120/70-R19 front, 170/60-R17 rear',
        },
        features: ['ShiftCam Technology', 'Dynamic ESA', 'ASC Traction Control', 'ABS Pro', 'Ride Modes Pro', 'Heated Grips'],
      },
      {
        modelName: 'Duke 390',
        brand: 'KTM',
        price: 299000,
        engineCapacity: '373cc',
        image: 'bike8.jpg',
        category: 'Naked',
        color: 'Orange',
        availability: true,
        description: 'The most exciting entry-level street fighter with superbike DNA.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, single-cylinder',
          power: '43 bhp @ 9,000 rpm',
          torque: '37 Nm @ 7,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '13.4 litres',
          weight: '149 kg',
          topSpeed: '167 km/h',
          brakes: 'Single disc front, single disc rear',
          suspension: 'WP APEX inverted fork, WP APEX rear',
          tyres: '110/70-R17 front, 150/60-R17 rear',
        },
        features: ['Cornering ABS', 'Traction Control', 'Ride-By-Wire', 'Supermoto Mode', 'TFT Display', 'Quick Shifter'],
      },
      {
        modelName: 'YZF-R1',
        brand: 'Yamaha',
        price: 2039000,
        engineCapacity: '998cc',
        image: 'bike9.jpg',
        category: 'Sport',
        color: 'Yamaha Blue',
        availability: true,
        description: 'Born from MotoGP, the R1 features crossplane engine technology for ultimate track performance.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, crossplane inline-4',
          power: '200 bhp @ 13,500 rpm',
          torque: '113.3 Nm @ 11,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '17 litres',
          weight: '201 kg',
          topSpeed: '299 km/h',
          brakes: 'Dual disc front, single disc rear',
          suspension: 'KYB inverted fork, KYB rear',
          tyres: '120/70-ZR17 front, 190/55-ZR17 rear',
        },
        features: ['IMU', 'Traction Control', 'Slide Control', 'Launch Control', 'Quick Shift', 'Brake Control'],
      },
      {
        modelName: 'Hayabusa',
        brand: 'Suzuki',
        price: 1690000,
        engineCapacity: '1340cc',
        image: 'bike10.jpg',
        category: 'Sport',
        color: 'Glass Sparkle Black',
        availability: true,
        description: 'The ultimate sportbike, legendary for its aerodynamic design and immense power.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '190 bhp @ 9,700 rpm',
          torque: '150 Nm @ 7,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '20 litres',
          weight: '266 kg',
          topSpeed: '299 km/h (limited)',
          brakes: 'Brembo Stylema calipers front',
          suspension: 'KYB inverted fork, KYB rear shock',
          tyres: '120/70-ZR17 front, 190/50-ZR17 rear',
        },
        features: ['Suzuki Intelligent Ride System', 'Launch Control', 'Cruise Control', 'Hill Hold Control'],
      },
      {
        modelName: 'Street Triple RS',
        brand: 'Triumph',
        price: 1181000,
        engineCapacity: '765cc',
        image: 'bike11.jpg',
        category: 'Naked',
        color: 'Silver Ice',
        availability: true,
        description: 'The ultimate performance street bike, with Moto2 derived engine and track-ready specs.',
        specifications: {
          engine: 'Liquid-cooled, 12 valve, inline 3-cylinder',
          power: '130 bhp @ 12,000 rpm',
          torque: '80 Nm @ 9,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '15 litres',
          weight: '188 kg',
          topSpeed: '240 km/h',
          brakes: 'Brembo Stylema front calipers',
          suspension: 'Showa BPF front, Öhlins STX40 rear',
          tyres: '120/70-ZR17 front, 180/55-ZR17 rear',
        },
        features: ['TFT Connectivity', 'Optimised Cornering ABS', 'Triumph Shift Assist', '5 Riding Modes'],
      },
      {
        modelName: 'Z900',
        brand: 'Kawasaki',
        price: 920000,
        engineCapacity: '948cc',
        image: 'bike12.jpg',
        category: 'Naked',
        color: 'Metallic Spark Black',
        availability: true,
        description: 'The Sugomi-styled supernaked that balances power and handling perfectly.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '125 bhp @ 9,500 rpm',
          torque: '98.6 Nm @ 7,700 rpm',
          transmission: '6-speed',
          fuelCapacity: '17 litres',
          weight: '212 kg',
          topSpeed: '240 km/h',
          brakes: 'Dual semi-floating 300 mm discs front',
          suspension: 'Inverted fork, horizontal back-link rear',
          tyres: '120/70-ZR17 front, 180/55-ZR17 rear',
        },
        features: ['KTRC', 'Power Modes', 'TFT Color Instrumentation', 'Smartphone Connectivity'],
      },
      {
        modelName: 'Streetfighter V4 S',
        brand: 'Ducati',
        price: 2462000,
        engineCapacity: '1103cc',
        image: 'bike13.jpg',
        category: 'Naked',
        color: 'Ducati Red',
        availability: true,
        description: 'The Panigale V4 stripped of its fairings, equipped with high handlebars and biplane wings.',
        specifications: {
          engine: 'Desmosedici Stradale V4',
          power: '208 bhp @ 13,000 rpm',
          torque: '123 Nm @ 9,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '17 litres',
          weight: '197 kg',
          topSpeed: '299 km/h',
          brakes: 'Brembo Stylema monobloc',
          suspension: 'Öhlins NIX30 front, Öhlins TTX36 rear',
          tyres: '120/70-ZR17 front, 200/60-ZR17 rear',
        },
        features: ['Biplane Wings', 'Öhlins Smart EC 2.0', 'Cornering ABS EVO', 'Ducati Traction Control EVO 2'],
      },
      {
        modelName: 'CB1000R Black Edition',
        brand: 'Honda',
        price: 1550000,
        engineCapacity: '998cc',
        image: 'bike14.jpg',
        category: 'Naked',
        color: 'Graphite Black',
        availability: true,
        description: 'Neo Sports Café styling with an aggressive blacked-out finish and Fireblade-derived power.',
        specifications: {
          engine: 'Liquid-cooled, DOHC inline-4',
          power: '143 bhp @ 10,500 rpm',
          torque: '104 Nm @ 8,250 rpm',
          transmission: '6-speed',
          fuelCapacity: '16.2 litres',
          weight: '212 kg',
          topSpeed: '230 km/h',
          brakes: 'Dual radial mount calipers front',
          suspension: 'Showa SFF-BP fork, Showa BRFC rear',
          tyres: '120/70-ZR17 front, 190/55-ZR17 rear',
        },
        features: ['Quick Shifter', 'Machined Details', 'TFT Display', 'Honda Smartphone Voice Control'],
      },
      {
        modelName: 'RSV4 1100 Factory',
        brand: 'Aprilia',
        price: 2369000,
        engineCapacity: '1099cc',
        image: 'bike15.jpg',
        category: 'Sport',
        color: 'Aprilia Black',
        availability: true,
        description: 'Uncompromising track weapon with a narrow V4 engine and advanced integrated aerodynamics.',
        specifications: {
          engine: 'Longitudinal 65° V-4 cylinder',
          power: '217 bhp @ 13,000 rpm',
          torque: '125 Nm @ 10,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '17.9 litres',
          weight: '202 kg',
          topSpeed: '305 km/h',
          brakes: 'Brembo Stylema calipers',
          suspension: 'Öhlins Smart EC 2.0 electronic suspension',
          tyres: '120/70-ZR17 front, 200/55-ZR17 rear',
        },
        features: ['Integrated Winglets', 'APRC System', 'Engine Maps', 'Wheelie Control', 'Cornering ABS'],
      },
      {
        modelName: 'F3 800 RC',
        brand: 'MV Agusta',
        price: 2199000,
        engineCapacity: '798cc',
        image: 'bike16.jpg',
        category: 'Sport',
        color: 'Reparto Corse Red/White',
        availability: true,
        description: 'Motorcycle art combining a counter-rotating crankshaft triple with stunning Italian design.',
        specifications: {
          engine: 'Three-cylinder, 4-stroke, 12-valve',
          power: '147 bhp @ 13,000 rpm',
          torque: '88 Nm @ 10,100 rpm',
          transmission: '6-speed, cassette style',
          fuelCapacity: '16.5 litres',
          weight: '173 kg (dry)',
          topSpeed: '240 km/h',
          brakes: 'Brembo radial monobloc calipers',
          suspension: 'Marzocchi inverted fork, Sachs rear',
          tyres: '120/70-ZR17 front, 180/55-ZR17 rear',
        },
        features: ['Counter-rotating Crankshaft', 'MVICS 2.0', 'Traction Control', 'EAS 3.0 Quick Shift'],
      },
      {
        modelName: 'R 18',
        brand: 'BMW',
        price: 1990000,
        engineCapacity: '1802cc',
        image: 'bike17.jpg',
        category: 'Cruiser',
        color: 'Black Storm Metallic',
        availability: true,
        description: 'A heritage cruiser built around the largest boxer engine BMW has ever produced.',
        specifications: {
          engine: 'Air/oil-cooled two-cylinder boxer',
          power: '91 bhp @ 4,750 rpm',
          torque: '158 Nm @ 3,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '16 litres',
          weight: '345 kg',
          topSpeed: '180 km/h',
          brakes: 'Twin disc front, single disc rear',
          suspension: 'Telescopic fork, steel swinging fork',
          tyres: '120/70-R19 front, 180/65-B16 rear',
        },
        features: ['Exposed Drive Shaft', 'Three Riding Modes (Rain, Roll, Rock)', 'Keyless Ride', 'ASC'],
      },
      {
        modelName: '1290 Super Duke R',
        brand: 'KTM',
        price: 2296000,
        engineCapacity: '1301cc',
        image: 'bike18.jpg',
        category: 'Naked',
        color: 'KTM Orange',
        availability: true,
        description: 'The Beast. A radical naked bike with mind-bending V-twin torque and a lightweight chassis.',
        specifications: {
          engine: 'Liquid-cooled, 2-cylinder, 4-stroke, V 75°',
          power: '180 bhp @ 9,500 rpm',
          torque: '140 Nm @ 8,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '16 litres',
          weight: '189 kg (dry)',
          topSpeed: '280 km/h',
          brakes: 'Brembo Stylema monobloc',
          suspension: 'WP APEX 48 front, WP APEX rear shock',
          tyres: '120/70-ZR17 front, 200/55-ZR17 rear',
        },
        features: ['Motor Slip Regulation', 'Cornering ABS', 'Supermoto ABS', 'KTM MY RIDE', 'Track Mode'],
      },
      {
        modelName: 'Scout Bobber',
        brand: 'Indian',
        price: 1350000,
        engineCapacity: '1133cc',
        image: 'bike19.jpg',
        category: 'Cruiser',
        color: 'Thunder Black Smoke',
        availability: true,
        description: 'Stripped down, blacked out, and built for an aggressive riding position.',
        specifications: {
          engine: 'Liquid-cooled V-Twin',
          power: '100 bhp',
          torque: '97.7 Nm @ 6,000 rpm',
          transmission: '6-speed',
          fuelCapacity: '12.5 litres',
          weight: '252 kg',
          topSpeed: '190 km/h',
        },
        features: ['ABS', 'Bobber Style Seat', 'Low Slung Stance'],
      },
      {
        modelName: 'Bonneville T120',
        brand: 'Triumph',
        price: 1100000,
        engineCapacity: '1200cc',
        image: 'bike20.jpg',
        category: 'Naked',
        color: 'Jet Black',
        availability: true,
        description: 'The definitive British motorcycle icon, combining timeless style with modern capabilities.',
        specifications: {
          engine: 'Liquid-cooled, 8-valve, parallel-twin',
          power: '80 bhp @ 6,550 rpm',
          torque: '105 Nm @ 3,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '14.5 litres',
          weight: '236 kg',
          topSpeed: '185 km/h',
        },
        features: ['Ride-by-wire', 'ABS', 'Traction Control', 'Cruise Control'],
      },
      {
        modelName: 'YZF-R6',
        brand: 'Yamaha',
        price: 1550000,
        engineCapacity: '599cc',
        image: 'bike21.jpg',
        category: 'Sport',
        color: 'Icon Blue',
        availability: true,
        description: 'The ultimate 600cc supersport bike, featuring aerodynamic styling and screaming performance.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '118.4 bhp @ 14,500 rpm',
          torque: '61.7 Nm @ 10,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '17 litres',
          weight: '190 kg',
          topSpeed: '260 km/h',
        },
        features: ['TCS', 'QSS', 'YCC-T', 'D-Mode'],
      },
      {
        modelName: 'CBR600RR',
        brand: 'Honda',
        price: 1450000,
        engineCapacity: '599cc',
        image: 'bike22.jpg',
        category: 'Sport',
        color: 'Grand Prix Red',
        availability: true,
        description: 'A pure track weapon brought to the street, perfectly balancing power and handling.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '121 bhp @ 14,000 rpm',
          torque: '63 Nm @ 11,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '18 litres',
          weight: '194 kg',
          topSpeed: '255 km/h',
        },
        features: ['HSTC', 'Cornering ABS', 'Wheelie Control'],
      },
      {
        modelName: 'Ninja 650',
        brand: 'Kawasaki',
        price: 720000,
        engineCapacity: '649cc',
        image: 'bike23.jpg',
        category: 'Sport',
        color: 'Lime Green',
        availability: true,
        description: 'An aggressive, sporty styling paired with a punchy parallel-twin engine for everyday riding.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, parallel-twin',
          power: '68 bhp @ 8,000 rpm',
          torque: '64 Nm @ 6,700 rpm',
          transmission: '6-speed',
          fuelCapacity: '15 litres',
          weight: '196 kg',
          topSpeed: '210 km/h',
        },
        features: ['TFT Display', 'Smartphone Connectivity', 'KTRC'],
      },
      {
        modelName: 'Monster',
        brand: 'Ducati',
        price: 1250000,
        engineCapacity: '937cc',
        image: 'bike24.jpg',
        category: 'Naked',
        color: 'Ducati Red',
        availability: true,
        description: 'The essence of Ducati in its most compact, essential, and lightest form.',
        specifications: {
          engine: 'Testastretta 11°, V2',
          power: '111 bhp @ 9,250 rpm',
          torque: '93 Nm @ 6,500 rpm',
          transmission: '6-speed',
          fuelCapacity: '14 litres',
          weight: '188 kg',
          topSpeed: '225 km/h',
        },
        features: ['Cornering ABS', 'Ducati Quick Shift', 'TFT Display'],
      },
      {
        modelName: 'GSX-R1000R',
        brand: 'Suzuki',
        price: 1980000,
        engineCapacity: '999cc',
        image: 'bike25.jpg',
        category: 'Sport',
        color: 'Metallic Triton Blue',
        availability: true,
        description: 'The King of Sportbikes, offering immense power and track-ready suspension.',
        specifications: {
          engine: 'Liquid-cooled, 4-stroke, inline-4',
          power: '202 bhp @ 13,200 rpm',
          torque: '117.6 Nm @ 10,800 rpm',
          transmission: '6-speed',
          fuelCapacity: '16 litres',
          weight: '203 kg',
          topSpeed: '299 km/h',
        },
        features: ['VVT', 'Bi-directional Quick Shift', 'Launch Control'],
      },
      // Coming Soon Bikes
      {
        modelName: 'S 1000 RR M',
        brand: 'BMW',
        price: 2850000,
        engineCapacity: '999cc',
        image: 'bike-cs1.jpg',
        category: 'Sport',
        color: 'M Motorsport',
        availability: false,
        comingSoon: true,
        expectedLaunchDate: new Date('2025-03-15'),
        description: 'Next-generation M superbike with all-new aerodynamics and chassis.',
        specifications: {},
        features: ['New M Suspension', 'Active Winglets', 'M Ride Modes', 'Shift Assist Pro'],
      },
      {
        modelName: 'Panigale V6',
        brand: 'Ducati',
        price: 3500000,
        engineCapacity: '1158cc',
        image: 'bike-cs2.jpg',
        category: 'Sport',
        color: 'Ducati Red',
        availability: false,
        comingSoon: true,
        expectedLaunchDate: new Date('2025-06-01'),
        description: 'The future of superbikes — prototype V6 engine with 240+ bhp.',
        specifications: {},
        features: ['V6 Engine', 'Active Aerodynamics', 'AI Traction Control', 'Carbon Fiber Bodywork'],
      },
      {
        modelName: 'ZX-10R 2025',
        brand: 'Kawasaki',
        price: 1799000,
        engineCapacity: '998cc',
        image: 'bike-cs3.jpg',
        category: 'Sport',
        color: 'Emerald Blazed Green',
        availability: false,
        comingSoon: true,
        expectedLaunchDate: new Date('2025-01-20'),
        description: 'Completely redesigned ZX-10R with new aerodynamics and electronics package.',
        specifications: {},
        features: ['New Aerodynamic Bodywork', 'KCMF 2.0', 'Cornering Management Function', 'New TFT Display'],
      },
    ]);

    console.log(`✅ ${bikes.length} bikes seeded (25 available, 3 coming soon)`);

    // ─── Services ────────────────────────────────────────
    const services = await Service.insertMany([
      {
        serviceName: 'General Service',
        description: 'Comprehensive inspection and maintenance of all major components including oil change, filter replacement, and chain adjustment.',
        price: 2500,
        duration: '2-3 hours',
        category: 'Maintenance',
        icon: 'wrench',
      },
      {
        serviceName: 'Oil Change',
        description: 'Engine oil and filter replacement using premium grade synthetic oil for optimal performance and engine longevity.',
        price: 800,
        duration: '30-45 minutes',
        category: 'Maintenance',
        icon: 'droplet',
      },
      {
        serviceName: 'Engine Repair',
        description: 'Complete engine diagnostics, teardown, repair, and reassembly by certified mechanics with OEM parts.',
        price: 8000,
        duration: '1-3 days',
        category: 'Repair',
        icon: 'settings',
      },
      {
        serviceName: 'Brake Service',
        description: 'Brake pad inspection and replacement, brake fluid flush, rotor resurfacing or replacement for safe stopping power.',
        price: 1500,
        duration: '1-2 hours',
        category: 'Maintenance',
        icon: 'disc',
      },
      {
        serviceName: 'Electrical Repair',
        description: 'Full electrical system diagnostics and repair including wiring, battery, charging system, and ECU diagnostics.',
        price: 3500,
        duration: '2-4 hours',
        category: 'Electrical',
        icon: 'zap',
      },
      {
        serviceName: 'Full Inspection',
        description: 'Comprehensive 50-point inspection covering engine, brakes, tyres, electronics, and safety systems with detailed report.',
        price: 1200,
        duration: '2-3 hours',
        category: 'Inspection',
        icon: 'search',
      },
    ]);

    console.log(`✅ ${services.length} services seeded`);

    console.log('\n🎉 Seeding complete!\n');
    console.log('Admin credentials:');
    console.log('  Email:    admin@motorbike.com');
    console.log('  Password: admin123');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error.message);
    process.exit(1);
  }
};

seed();
